=== boom-sakalaka/Java_Demo/xmlProj/src/hr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT hr (employee+)>
<!ELEMENT employee (name,age,salary,department)>
<!ATTLIST employee no CDATA "">
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT department (dname,address)>
<!ELEMENT dname (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== boom-sakalaka/Java_Demo/xmlProj/src/hr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hr SYSTEM "hr.dtd">
<!-- 人力资源管理系统 -->
<hr>
	<employee no="1111">
		<name>张三</name>
		<age>31</age>
		<salary>4000</salary>
		<department>
			<dname>会计部</dname>
			<address>xx大夏-B103</address>
		</department>
	</employee>
	<employee>
		<name>李四</name>
		<age>33</age>
		<salary>6000</salary>
		<department>
			<dname>工程部</dname>
			<address>xx大夏-B105</address>
		</department>
	</employee>
</hr>
